catalog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    # path('lista_de_livros/', views.lista_de_livros, name="lista_de_livros"),
    path('livros/', views.ListaDeLivros.as_view(), name="livros"),
    re_path(r'^livro/(?P<pk>\d+)$', views.DetalhesDoLivro.as_view(), name="detalhe-livro"),
    path('autores/', views.ListaDeAutores.as_view(), name="autores"),
    re_path(r'^autor/(?P<pk>\d+)$', views.DetalhesDoAutor.as_view(), name="detalhe-autor"),
    path('meuslivros/', views.LivrosEmprestadosAoUsuário.as_view(), name="meus-emprestados"),
    path('livrosemprestados', views.LivrosEmprestados.as_view(), name="todos-emprestados"),
    path('livro/<uuid:pk>/renovar/', views.renovar_livro, name="renovar-livro"),

    path('autor/criar/', views.AutorCreate.as_view(), name="criar-autor"),
    path('autor/<int:pk>/atualizar/', views.AutorUpdate.as_view(), name="atualizar-autor"),
    path('autor/<int:pk>/excluir/', views.AutorDelete.as_view(), name="excluir-autor"),

    path('ferramentas/', views.ferramentas, name="ferramentas"),

    path('livro/criar/', views.LivroCreate.as_view(), name="criar-livro"),
    re_path(r'^livro/(?P<pk>[a-zA-Z0-9-]+)/atualizar/', views.LivroUpdate.as_view(), name="atualizar-livro"), # using regular expressions to find the uuid
    re_path(r'^livro/(?P<pk>[a-zA-Z0-9-]+)/excluir/', views.LivroDelete.as_view(), name="excluir-livro"),

]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')), # inclui as urls da aplicação 'catalog' para processar as urls subsequentes a 'catalog/'
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('contas/', include('django.contrib.auth.urls'))
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Gênero(models.Model):
    nome = models.CharField(max_length=200, help_text='Insira um gênero (ex. Ficção científica).')

    def __str__(self):
        return self.nome

class Idioma(models.Model):
    nome = models.CharField(max_length=100, help_text='Insira o idioma da versão (ex. Francês, Inglês, Japonês).')

    def __str__(self):
        return self.nome

class Livro(models.Model):
    título = models.CharField(max_length=200, help_text='Insira o título.')
    autor = models.ForeignKey('autor', help_text='Insira o autor.', on_delete=models.SET_NULL, null=True)
    resumo = models.TextField(max_length=1000, help_text='Insira a descrição do título.')
    isbn = models.CharField('ISBN', max_length=13, help_text='<a href="http://www.isbn.bn.br/website/" target="_blank">Número do ISBN</a> de 13 caractéres.')
    gênero = models.ManyToManyField(Gênero, help_text='Insira o gênero do livro.')
    data_de_publicação = models.DateField(auto_now_add=True)

    def mostrar_gênero(self):
        """Cria um string pro gênero do livro. Requerido porque
        'gênero' é um campo ManyToMany e portanto não aceito."""
        return ', '.join(gênero.nome for gênero in self.gênero.all()[:3])

    mostrar_gênero.descrição_curta = 'Gênero'

    def __str__(self):
        return self.título

    def get_absolute_url(self):
        return reverse('detalhe-livro', args=[str(self.id)])

    class Meta:
        ordering = ['título', '-data_de_publicação']

class LivroInstância(models.Model):
    id = models.UUIDField(primary_key=True, default = uuid.uuid4, help_text='ID do livro nesta biblioteca.')
    livro = models.ForeignKey('Livro', on_delete=models.SET_NULL, null=True)
    impressão = models.CharField(max_length=200)
    data_de_devolução = models.DateField(null=True, blank=True)
    idioma = models.ManyToManyField(Idioma, help_text="Insira o idioma do livro.")
    locatário = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.data_de_devolução and date.today() > self.data_de_devolução:
            return True
        return False

    ESTADO_EMPRÉSTIMO = (
        ('m', 'Manutenção'),
        ('e', 'Emprestado'),
        ('d', 'Disponível'),
        ('r', 'Reservado'),
    )

    estado = models.CharField(max_length=1, choices=ESTADO_EMPRÉSTIMO, blank=True, default='m', help_text='Disponibilidade do título')

    class Meta:
        ordering = ['data_de_devolução']
        permissions = (("can_mark_returned", "Set book as returned"),("can_renew", "Can set the data_de_devolução"),("can_edit_content", "Can create, update and delete content"),)
    
    def __str__(self):
        return f"{self.id}: {self.livro.título}"

class Autor(models.Model):
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    nascimento = models.DateField(null=True, blank=True)
    morte = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['sobrenome', 'nome']

    # def get_absolute_url(self):
    #     return reverse('detalhe-autor', args=[{str(self.id)}]) # QUE ISSO SIRVA DE EXEMPLO FDP! PRESTENÇÃO!
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('detalhe-autor', args=[str(self.id)])

    def __str__(self):
        return f"{self.sobrenome}, {self.nome}"

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# class RenovarLivroForm(forms.Form):
#     data_de_renovação = forms.DateField(help_text="Insira uma data entre hoje e 4 semanas (padrão: 3).")

#     def clean_data_de_renovação(self):
#         """valida a data_de_renovação"""
#         data = self.cleaned_data['data_de_renovação'] # limpa a data de inputs potencialmente inseguros

#         # checa se a data não está no passado
#         if data < datetime.date.today():
#             raise ValidationError(_('Data inválida - renovação está no passado.'))

#         # checa se a data está dentro do lapso permitida
#         if data > datetime.date.today() + datetime.timedelta(weeks=4):
#             raise ValidationError(_('Data inválida - renovação superior a 4 semanas.')) # The example wraps this text in one of Django's translation functions ugettext_lazy() (imported as _()), which is good practice if you want to translate your site later.

#         # lembre-se de sempre retornar a data 'limpa'
#         return data

from django.forms import ModelForm
from catalog.models import LivroInstância

# forma simples de criar forms usando os fields de um Model apenas:
class RenovarLivroForm(ModelForm):

    def clean_data_de_renovação(self):
        """valida a data_de_renovação"""
        data = self.cleaned_data['data_de_devolução'] # limpa a data de inputs potencialmente inseguros

        # checa se a data não está no passado
        if data < datetime.date.today():
            raise ValidationError(_('Data inválida - renovação está no passado.'))

        # checa se a data está dentro do lapso permitida
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Data inválida - renovação superior a 4 semanas.')) # The example wraps this text in one of Django's translation functions ugettext_lazy() (imported as _()), which is good practice if you want to translate your site later.

        # lembre-se de sempre retornar a data 'limpa'
        return data

    class Meta:
        model = LivroInstância
        fields = ['data_de_devolução'] # como no exemplo de form para criar posts no djangogirls
        help_texts = {'data_de_devolução': _('Insira uma data entre hoje e 4 semanas (padrão 3).')} 

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Gênero, Idioma, Livro, LivroInstância, Autor
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.

# @login_required ---> to restrict access to logged users on view functions
def index(request):

    num_livros = Livro.objects.all().count()
    num_instâncias = LivroInstância.objects.all().count()
    num_instâncias_disponíveis = LivroInstância.objects.filter(estado__exact='d').count() #Livros disponíveis (estado == 'd')
    num_autores = Autor.objects.all().count()
    num_gêneros = Gênero.objects.all().count()
    num_livros_maionese = Livro.objects.filter(título__icontains='maionese').count()
    num_visitas = request.session.get('num_visitas', 0)

    request.session['num_visitas'] = num_visitas + 1

    context = {
        'num_livros': num_livros,
        'num_instâncias': num_instâncias,
        'num_instâncias_disponíveis': num_instâncias_disponíveis,
        'num_autores': num_autores,
        'num_gêneros': num_gêneros,
        'num_livros_maionese': num_livros_maionese,
        'num_visitas': num_visitas,
    }

    return render(request, 'index.html', context=context) # Context is a python dictionary {} containing the date to insert into the template

# def lista_de_livros(request):
#     lista_de_livros = Livro.objects.all()
#     return render(request, 'lista_de_livros.html', {'lista_de_livros' : lista_de_livros})
class ListaDeLivros(LoginRequiredMixin, generic.ListView):
    model = Livro
    paginate_by = 10
    
class DetalhesDoLivro(LoginRequiredMixin, generic.DetailView):
    model = Livro

class ListaDeAutores(LoginRequiredMixin, generic.ListView):
    model = Autor
    paginate_by = 10

class DetalhesDoAutor(LoginRequiredMixin, generic.DetailView):
    model = Autor

class LivrosEmprestadosAoUsuário(LoginRequiredMixin, generic.ListView):
    model = LivroInstância
    template_name = 'catalog/livroinstância_lista_emprestado_usuário.html'
    paginate_by = 10

    def get_queryset(self):
        return LivroInstância.objects.filter(locatário=self.request.user).filter(estado__exact='e').order_by('data_de_devolução')

class LivrosEmprestados(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = LivroInstância
    template_name = 'catalog/livroinstância_lista_emprestado.html'
    paginate_by = 10

    def get_queryset(self):
        return LivroInstância.objects.filter(estado__exact='e').order_by('data_de_devolução')

###############################################################################################################################
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import RenovarLivroForm # Import from forms
import datetime

@permission_required("catalog.can_renew")
def renovar_livro(request, pk):
    livro_instância = get_object_or_404(LivroInstância, pk=pk)

    if request.method == 'POST': # If this is a POST request then process the Form data
        form = RenovarLivroForm(request.POST) # Create a form instance and populate it with data from the request (binding)

        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            # livro_instância.data_de_devolução = form.cleaned_data['data_de_renovação']
            livro_instância.data_de_devolução = form.cleaned_data['data_de_devolução']
            livro_instância.save()

            return HttpResponseRedirect(reverse("todos-emprestados")) # redirect to a new URL (reverse() is the python equivalent to the url tag)

    # If this is a GET (or any other method) create the default form.
    else:
        data_de_renovação_proposta = datetime.date.today() + datetime.timedelta(weeks=3)
        # form = RenovarLivroForm(initial={'data_de_renovação': data_de_renovação_proposta})
        form = RenovarLivroForm(initial={'data_de_devolução': data_de_renovação_proposta})

    context = {
        'form': form,
        'livro_instância': livro_instância,
    }

    return render(request, 'catalog/renovar.html', context)

#######################################################  EDIÇÃO DE AUTORES  ############################################################3

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

class AutorCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_edit_content'
    model = Autor
    fields = '__all__'
    initial = {'morte': '29/11/2019'}
    template_name_suffix = '_formulário' # o nome padrão do HTML é 'nome_do_meu_modelo'_form.html. template_name_suffix é usado para mudar isso.

class AutorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_edit_content'
    model = Autor
    fields = ['nome','sobrenome','nascimento','morte'] # same as '__all__', but lengthier.
    template_name_suffix = '_formulário'

class AutorDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_edit_content'
    model = Autor
    success_url = reverse_lazy('autores')
    template_name_suffix = '_confirmar_exclusão'

################## FERRAMENTAS ADMINISTRATIVAS #####################

@permission_required('catalog.can_edit_content')
def ferramentas(request):
    context = {}
    return render(request, 'ferramentas.html', context=context)

############################################ EDIÇÃO LIVROS #############################################################

class LivroCreate(PermissionRequiredMixin, CreateView):
    permission_required = "catalog.can_edit_content"
    model = LivroInstância
    fields = "__all__"
    template_name_suffix = "_formulário"

class LivroUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "catalog.can_edit_content"
    model = LivroInstância
    fields = "__all__"
    template_name_suffix = "_formulário"

class LivroDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "catalog.can_edit_content"
    model = LivroInstância
    success_url = reverse_lazy('livros')
    template_name_suffix = "_confirmar_exclusão"

templates/catalog/autor_confirmar_exclusão.html
{% extends 'base.html' %}

{% block content %}
    <h1>Excluir Autor</h1>

    <p>Tem certeza de que deseja excluir o autor: {{ autor.nome }} {{ autor.sobrenome }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Sim, excluir.">
    </form>

{% endblock %}

templates/catalog/autor_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>Biblioteca Local</title>
{% endblock %}

{% block content %}
    <h1>Autor: {{autor.nome}} {{autor.sobrenome}} </h1>

    {% if perms.catalog.can_edit_content %}
    <p><a href="{% url 'atualizar-autor' autor.pk %}"><i class="far fa-edit"> Atualizar</i></a></p>
    <p><a href="{% url 'excluir-autor' autor.pk %}"><i class="far fa-trash-alt"> Excluir</i></a></p>
    {% endif %}

    <p><strong>Data de nascimento: </strong>
        {% if autor.nascimento %}
            {{ autor.nascimento }}
        {% else %}
            --
        {% endif %}
    </p>
    <p><strong>Data da morte: </strong>
        {% if autor.morte %}
            {{ autor.morte }}
        {% else %}
            --
        {% endif %}
    </p>

    <div style="margin-left:20px; margin-top:20px;">
        <h4>Obras deste autor na biblioteca:</h4>
        {% if autor.livro_set.all %}
            {% for obra in autor.livro_set.all %}
                <hr>
                <h4><a href="{% url 'detalhe-livro' obra.pk %}">{{ obra.título }}</a></h4>
                <p><strong>Resumo: </strong>{{ obra.resumo }}</p>
                <p><strong>ISBN: </strong>{{ obra.isbn }}</p>
            {% endfor %}
        {% else %}
            <p class="text-danger">Não há obras deste autor no banco de dados.</p>
        {% endif %}
    </div>

{% endblock %}

templates/catalog/autor_formulário.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Atualizar">
    </form>

{% endblock %}

templates/catalog/autor_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Biblioteca Local</title>
{% endblock %}

{% block content %}
    <h1>Lista de Autores</h1>
        {% if autor_list %}
        <ul>
            {% for autor in autor_list %}
            <li><a href="{{autor.get_absolute_url}}">{{autor.nome}} {{autor.sobrenome}} 
                {% if autor.nascimento %}
                 ({{autor.nascimento}} - {{autor.morte}})
                {% endif %}
            </a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Nenhum autor encontrado.</p>
        {% endif %}
{% endblock %}

templates/catalog/livro_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>Biblioteca Local</title>
{% endblock %}

{% block content %}
    <h1>Título: {{livro.título}}</h1>

    <p><strong>Autor: </strong><a href="{% url 'detalhe-autor' livro.autor.pk %}">{{ livro.autor }}</a></p>
    <p><strong>Resumo: </strong>{{ livro.resumo }}</p>
    <p><strong>ISBN: </strong>{{ livro.isbn }}</p>
    <p><strong>Idioma: </strong>{{ livro.idioma.all }}</p>
    <p><strong>Gênero: </strong>{{ livro.gênero.all|join:", " }}</p>

    <div style="margin-left:20px; margin-top:20px;">
        <h4>Exemplares:</h4>

        {% for cópia in livro.livroinstância_set.all %} <!-- livro.livroinstância_set.all is automagically genned by django => returns all livroinstancias associated with a specific livro -->
            <hr>
            <p class="{% if cópia.estado == 'd' %}text-success{% elif cópia.estado == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ cópia.get_estado_display }}
            </p>
            {% if cópia.estado != 'd' %}
            <p><strong>Data prevista de devolução: </strong>{{ cópia.data_de_devolução }}</p>
            {% endif %}
            <p><strong>Impressão:</strong> {{ cópia.impressão }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ cópia.id }}</p>

            {% if perms.catalog.can_edit_content %}
            <p><a href="{% url 'atualizar-livro' cópia.pk %}"><i class="far fa-edit"> Atualizar</i></a></p>
            <p><a href="{% url 'excluir-livro' cópia.pk %}"><i class="far fa-trash-alt"> Excluir</i></a></p>
            {% endif %}

        {% endfor %}

    </div>

{% endblock %}

templates/catalog/livro_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Biblioteca Local</title>
{% endblock %}

{% block content %}
    <h1>Lista de Livros</h1>
        {% if livro_list %}
        <ul>
            {% for livro in livro_list %}
            <li><a href="{{ livro.get_absolute_url }}">{{livro.título}}</a href="{% url 'detalhe-autor' livro.autor.pk %}"> ({{livro.autor}})</li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Nenhum livro encontrado nesta biblioteca.</p>
        {% endif %}
{% endblock %}

templates/catalog/livroinstância_confirmar_exclusão.html
{% extends 'base.html' %}

{% block content %}
    <h1>Excluir Livro</h1>

    <p>Tem certeza de que deseja excluir o livro: {{ livroinstância }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Sim, excluir.">
    </form>
{% endblock %}

templates/catalog/livroinstância_formulário.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Atualizar">
    </form>
{% endblock %}

templates/catalog/livroinstância_lista_emprestado.html
{% extends 'base.html' %}

{% block content %}
    <h1>Livros Emprestados da Biblioteca:</h1>

    {% if livroinstância_list %}
    <ul>
        {% for livroins in livroinstância_list %}
        <li class="{% if livroins.is_overdue %}text-danger{% endif %}">
            
                {% if livroins.livro.título %}
                <a href="{% url 'detalhe-livro' livroins.livro.pk %}">{{livroins.livro.título}}</a> 
                {% else %}
                EXCLUÍDO
                {% endif %}
            ({{ livroins.data_de_devolução }}).
            <strong>Locatário:</strong>  
                {% if livroins.locatário %}
                <a href="javascript:void()">{{ livroins.locatário }}.</a>
                {% else %}
                NÃO INFORMADO
                {% endif %}
            {% if livroins.is_overdue %}<i style="{color: red;}" class="fas fa-exclamation-triangle"> ATRASADO!</i>
            {% endif %}
            {% if perms.catalog.can_renew %} - <i class="fas fa-calendar-plus"><a href="{% url 'renovar-livro' livroins.id %}"> Renovar</a></i>{% endif %}
        </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>Não há livros emprestados</p>
    {% endif %}

{% endblock %}

templates/catalog/livroinstância_lista_emprestado_usuário.html
{% extends 'base.html' %}

{% block content %}
    <h1>Livros Emprestados de {{ user.get_username }}:</h1>

    {% if livroinstância_list %}
    <ul>
        {% for livroins in livroinstância_list %}
        <li class="{% if livroins.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'detalhe-livro' livroins.livro.pk %}">{{livroins.livro.título}}</a> ({{ livroins.data_de_devolução }}). {% if livroins.is_overdue %}<i style="{color: red;}" class="fas fa-exclamation-triangle"> ATRASADO!</i>{% endif %}
        </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>Não há livros emprestados</p>
    {% endif %}

{% endblock %}

templates/catalog/renovar.html
{% extends 'base.html' %}

{% block content %}
    <h1>Renovar: {{ livro_instância.livro.título }}</h1>
    <p>Locatário: {{ livro_instância.locatário }}</p>
    <p {% if livro_instância.is_overdue %}class="text-danger"{% endif %}>Data de devolução: {{ livro_instância.data_de_devolução }}</p>

    <form action="" method="POST">{% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Atualizar">
    </form>

{% endblock %}